### ISSUE TITLE
How to use another storage option?

### ISSUE THREAD

**Issue by Krakor92** [FlameWolf/formzilla#2]
In the documentation, you say that there are 4 different types of storage options that you can choose when registering the plugin. But I can't import any of these classes at the moment.
It seems that your index.js uses StreamStorage() by default with no possibility to change it in our code :

https://github.com/FlameWolf/formzilla/blob/75ffb489fb2053153f925fa38f36fd3b779b4667/index.js#L14-L15

Did I miss something ?

**Comment by FlameWolf** [comment]
When you register the plugin, you pass an additional parameter like this:

```jsx
server.register(formDataParser, {
	storage: new DiscStorage(file => {
		return {
			directory: path.join(__dirname, "public"),
			fileName: file.originalName.toUpperCase()
		};
	})
});
```

**Comment by Krakor92** [comment]
Oh yeah, I didn't realize it was a default variable in case the storage property was missing.
I was also confused by the import syntax. Is there a reason why you don't bundle the export of your Storages classes in your index.js?

It would be nice so we don't have to look at the directory structure of your plugin. That way, we could just import like this:
```js
import formzilla, { DiscStorage } from "formzilla";
```
