### ISSUE TITLE
Fastify 4.11.0 supported?

### ISSUE THREAD

**Issue by leppaott** [FlameWolf/formzilla#3]
Hey, just tried this with `fastify 4.11.0` and got immediately following upon importing and building the package, only importing was enough.

```
Type 'FormDataParserPlugin' is not assignable to type 'FastifyPluginCallback<FastifyPluginOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
  Types of parameters 'instance' and 'instance' are incompatible.
    Type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>' is missing the following properties from type 'FastifyInstance<RawServerDefault, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault>': addresses, hasPlugin
```

Yeah it works if I also lock formzilla's fastify version to the same version on package-lock. But anyway just updated fastify to the latest and now it works! Yeah this probably on 4.13 broke the version compatibility https://github.com/fastify/fastify/pull/4527 
So all is good.

Just wanted to say good job on the plugin seems much more leaner than the fastify/multi-part which we too used for a while and realized preValidation hooks are going to be pain in the ass without something like this.

**Comment by FlameWolf** [comment]
I will look into this, thank you for reporting.
