### ISSUE TITLE
Array handling

### ISSUE THREAD

**Issue by brainwind-software** [FlameWolf/formzilla#5]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `formzilla@3.1.1` for the project I'm working on.

my problem was, that arrays were not correctly handled.
I tried different settings, but in the end I am sending an array from frontend now like this:
```array.forEach((val, i) => formData.append(`${key}[${i}]`, val))```

And added the following patch, so the array gets reconstructed correctly, before my schema validation runs:

```diff
diff --git a/node_modules/formzilla/index.js b/node_modules/formzilla/index.js
index a44baba..7564427 100644
--- a/node_modules/formzilla/index.js
+++ b/node_modules/formzilla/index.js
@@ -24,7 +24,22 @@ const formDataParser = async (instance, options) => {
 			body[name] = JSON.stringify(info);
 		});
 		bus.on("field", (name, value) => {
-			body[name] = parseField(name, value);
+			// if the name ends with [\d+], its an array element (save its name and index)
+			const match = name.match(/^(.+)\[(\d+)\]$/)
+			if (match) {
+				const arrayName = match[1]
+				const arrayIndex = parseInt(match[2], 10)
+
+				// if the array doesn't exist yet, create it
+				if (!body[arrayName]) {
+					body[arrayName] = []
+				}
+
+				// add the value to the array at the correct index
+				body[arrayName][arrayIndex] = parseField(arrayName, value);
+			} else {
+				body[name] = parseField(name, value);
+			}
 		});
 		finished(bus, (err = null) => {
 			Promise.all(results).then(files => {
```

**Comment by FlameWolf** [comment]
@brainwind-software Did you try changing your code like this?

`formData.append("array", JSON.stringify(array));`

**Comment by brainwind-software** [comment]
@FlameWolf 
Oh, thanks for the hint. This works.
I should have read the sourcecode better :)
