### ISSUE TITLE
FastifyDeprecation: request.routeSchema

### ISSUE THREAD

**Issue by leppaott** [FlameWolf/formzilla#6]
We're listening and terminating on process.warnings:

`FastifyDeprecation: You are accessing the deprecated "request.routeSchema" property. Use "request.routeOptions.schema" instead. Property "req.routeSchema" will be removed in `fastify@5`.`

Seems you already updated to latest fastify so perhaps that field accessing can be changed too?

**Comment by FlameWolf** [comment]
Sure, will update it! Thanks.

**Comment by leppaott** [comment]
Muchas gracias :+1: Your CI seems to be still failing.

**Comment by FlameWolf** [comment]
> Muchas gracias 👍 Your CI seems to be still failing.

Tap had some major changes in the new version. Fixed now.
